# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f7d07eb76392cffdc7c14d1e8358e9753de7def7720a8cd4c9e02000061593f9155303c05e8f2118d0400f13a885700cc951c9a77cbe5b30023d6c7857650e02

test:
  secret_key_base: 54c75e2180c3c597a5477ae006faaf739102e790366e23dbc5e70c6df5a27678e9515d0dee64af2c2ac62ce44fd31120ba9d0efbc666af6899785c3dfdec6f86

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
